name: Culture Ex Machina
title: Culture Ex Machina - A blog about machine learning, engineering, and other trivialities
description: A blog about machine learning, engineering, and other trivialities
meta_description: > #
 Max Schumacher's blog about learning, engineering, life and all the rest.

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl:
domain_name: https://cpury.github.io
google_analytics_key: UA-63484688-1
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: https://cpury.github.io/
author: Max Schumacher

social:
  name: Max Schumacher
  links:
    - https://www.linkedin.com/in/max-schumacher-530a216a/
    - https://github.com/cpury
    - https://angel.co/max-schumacher-1

gems:
  - jekyll-seo-tag
